// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // Plugins automatically generated by TLGradle.kt
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    id("com.gradle.plugin-publish") version "2.1.0"
   // id("com.vanniktech.maven.publish") version "0.36.0" apply false
    
}
/*
tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
*/